### PR TITLE
feat: resolve casdoor as SAML SP with keycloak login not work bug

### LINKED ISSUE #1894: Casdoor as SAML SP with keycloak login not work
Hi! I try to use Casdoor as SAML SP  with keycloak different version and casdoor can't login.

**In Keycloak 12.0.4 (version of our test environment)**

1. Create realm
image
2. Configure client connection
image
3. Download metadata files in moq auth format
4. Create new provider in casdoor
image

5. Try to login
image

**In Keycloack 21.1.1 (latest version running in docker with start-dev parameter)**

1. create realm
image
2. Configure client connection
image
image
image
3. Copy metadata SP from realm settings
4. Create new provider in casdoor
image
5. Try to login
image

I also tried to change the client ID from  full path to relative /api/acs, but that didn't help

### PR DESCRIPTION
**Pull request by XDTD**
fix #1894

### CODE REVIEW

**Comment by leo220yuyaodog** [comment]
@XDTD Can you provide a demo video about the login process?

**Comment by XDTD** [comment]
> @XDTD Can you provide a demo video about the login process?

Here is the demo video. Keycloak version is 21.1.1, which is running on Docker.

https://github.com/casdoor/casdoor/assets/34300181/5dae5dca-8ecc-4290-b6cc-115d18430434

**Comment by leo220yuyaodog** [comment]
@hsluoyz lgtm

File: object/provider.go [hunk 1]
```diff
@@ -225,7 +225,6 @@ func UpdateProvider(id string, provider *Provider) (bool, error) {
 		session = session.Omit("client_secret2")
 	}
 
-	provider.Endpoint = util.GetEndPoint(provider.Endpoint)
 	provider.IntranetEndpoint = util.GetEndPoint(provider.IntranetEndpoint)
```
Comment (leo220yuyaodog) [inline object/provider.go:228]: The codes here are about https://github.com/casdoor/casdoor/commit/96219442f57838324e9d9efff701669b6ca97142
Now it  looks like the pr breaks other provider such as SAML. Maybe you need to add an if condition to prevent the code breaks the fix in the https://github.com/casdoor/casdoor/commit/96219442f57838324e9d9efff701669b6ca97142

Comment (leo220yuyaodog) [reply object/provider.go:228]: @XDTD The pr works, but we need to compatible the fix in https://github.com/casdoor/casdoor/commit/96219442f57838324e9d9efff701669b6ca97142

Comment (XDTD) [reply object/provider.go]: Thx for ur advice. This pr has been updated. Pls review the changes.
